# Default values for demo-secrets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project_id: ""
google_service_account: "gke-workload"

adminAccount:
  name: "admin"
