apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: {{ .Values.adminAccount.name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/781365677071/secrets/flux-secret/versions/latest"
        path: "/var/secrets/good1.txt"
