apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adminAccount.name }}
  namespace: {{ .Values.adminAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.google_service_account | default "gke-workload" }}@{{ .Values.project_id | default "changeme" }}.iam.gserviceaccount.com

