apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./fluxcd/kustomize/middleware/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-nginx
  targetNamespace: ingress-nginx

