apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
      release: nginx
  template:
    metadata:
      labels:
        app: nginx
        release: nginx
    spec:
      containers:
      - name: nginx
        image: "nginx"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
